### ISSUE TITLE
perl-HTTP-Tinyish not installed automatically on Fedora 35

### ISSUE THREAD

**Issue by yasandev** [kiamazi/kateb#9]
After installing Kateb using the official installation method written on the README, I get this exception after running `kateb install all`:

```
Can't locate HTTP/Tinyish.pm in @INC (you may need to install the HTTP::Tinyish module) (@INC contains: /usr/local/lib64/perl5/5.34 /usr/local/share/perl5/5.34 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at /usr/local/share/perl5/5.34/kateb/Install.pm line 10.
BEGIN failed--compilation aborted at /usr/local/share/perl5/5.34/kateb/Install.pm line 10.
Compilation failed in require at /usr/local/share/perl5/5.34/kateb.pm line 8.
BEGIN failed--compilation aborted at /usr/local/share/perl5/5.34/kateb.pm line 8.
Compilation failed in require at /usr/local/bin/kateb line 15.
BEGIN failed--compilation aborted at /usr/local/bin/kateb line 15.
```

I fixed it for my own install by installing `perl-HTTP-Tinyish` package using DNF manually but it should be done automatically or given instructions for.

**Comment by kiamazi** [comment]
thank you for reporting the bug.
in the last patch, kateb switched from LWP to HTTP::Tinyish, but I changed the dependencies only in the cpan file and forgot to edit the MakeFile

patch v1.00.29
bug fix: added missing dependency

https://github.com/kiamazi/kateb/releases/tag/v1.00.29

**Comment by yasandev** [comment]
Great, thanks! But the readme is gone?!

**Comment by kiamazi** [comment]
hmmmm, really why? :thinking:

**Comment by yasandev** [comment]
It looks like you added it again lol, it was removed on your fix commit for this issue.

**Comment by kiamazi** [comment]
yes, that file was deleted and I really do not know why? :rofl:
